import {escapeHTML as e} from './lib.mjs?v=1.3.0';
import {decisionTable} from './field.mjs?v=1.3.0';

export function projectSummary(p){
  return `<section class="home-context" aria-labelledby="home-context-title"><div class="section-head"><div><span class="eyebrow">START WITH OUR OWN HOME</span><h2 id="home-context-title">先记住，我们装修的是这套房</h2></div><a href="#project">我家背景与推进顺序 ↗</a></div><div class="context-cards">${p.contextCards.map(c=>`<div><span class="eyebrow">${e(c.label)}</span><h3>${e(c.value)}</h3><p>${e(c.detail)}</p></div>`).join('')}</div><p class="hint">交房安排来自业主补充；交付不等于已恢复原状或可以立即拆旧。半包为当前倾向，具体分工待合同明确。</p></section>`;
}

export function projectBriefText(p){
  return `${p.title}\n\n${p.facts.join('\n')}\n\n请按半包意向提供同口径方案：人工和辅材、拆旧及清运、业主采购清单、设计与复尺、安装配合、验收售后分别列明；现场未核实项请标为待核或暂估，不直接包进笼统总价。\n\n现阶段房间需求：\n${p.roomNeeds.map(([name,need])=>name+'：'+need).join('\n')}\n\n${p.basis}`;
}

export function projectView(p){
  return `<header class="page-head"><span class="eyebrow">OUR RENOVATION BRIEF</span><h1 tabindex="-1">${e(p.title)}</h1><p>${e(p.summary)}</p></header><div class="hero-actions"><a class="primary" href="#house">按这套背景读实用攻略 ↗</a></div><section class="project-facts"><h2>目前知道的事</h2><ul>${p.facts.map(f=>`<li>${e(f)}</li>`).join('')}</ul><p class="hint">${e(p.basis)}</p></section><div class="section-head"><h2>按交房节点推进，不先锁死开工日</h2></div><div class="project-phases">${p.steps.map((s,i)=>`<section><span class="eyebrow">0${i+1} · ${e(s.label)}</span><h3>${e(s.title)}</h3><p>${e(s.body)}</p><ul>${s.checks.map(c=>`<li>${e(c)}</li>`).join('')}</ul><a href="#article/${e(s.articleId)}">看这一阶段的具体做法 ↗</a></section>`).join('')}</div><section class="project-section"><h2>倾向半包，先把责任说到一张表上</h2><p>下面是拿去询价的分工框架，不是“半包”一词自带的固定范围。公司之间只有逐项包到同一层、同一做法，价格才有可比性。</p>${decisionTable({caption:'横向比较：项目、要追问的范围与待落实责任',headers:['项目','询价时问清什么','本户分工与约定'],rows:p.packageScope})}<a href="#article/practical-budget-half-package-duties">阅读半包交接和责任划分 ↗</a></section><section class="project-section"><h2>此前户型需求，一起交给设计师</h2><dl class="room-brief">${p.roomNeeds.map(([name,need])=>`<div><dt>${e(name)}</dt><dd>${e(need)}</dd></div>`).join('')}</dl><p class="hint">这些是需求与条件方案，不是现场测量或准许拆改的结论；详细尺度继续参考现有模型与后续实测图。</p></section><section class="project-section"><h2>还需要补齐的几件事</h2><ol>${p.openQuestions.map(q=>`<li>${e(q)}</li>`).join('')}</ol></section><section class="project-brief"><h2>给候选装修公司的统一需求摘要</h2><p>把房子现状、半包意向和既定户型需求一次说明白，再请不同公司按同一范围回应。复制内容不包含购房合同或租客个人信息。</p><button type="button" data-copy-project>复制我家需求摘要</button></section><details class="article-evidence"><summary>背景的使用边界</summary><ul>${p.cautions.map(c=>`<li>${e(c)}</li>`).join('')}</ul></details><div class="field-links"><a href="#article/start-project-risk">本户优先风险 ↗</a><a href="#tools/compare">比较候选公司 ↗</a><a href="#tools/templates">交房与现场记录模板 ↗</a></div>`;
}
