// Scoped QA of this project's dedicated localhost tab; never follows references or downloads files.
// node tools/qa_storage_ui.mjs PORT TAB_ID [--images]
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
const [port,tabId,...flags]=process.argv.slice(2),requireImages=flags.includes('--images');
if(!/^\d+$/.test(port||'')||!tabId)throw new Error('Pass dedicated local CDP port and project tab ID');
const target=(await(await fetch(`http://127.0.0.1:${port}/json/list`)).json()).find(t=>t.id===tabId);
if(!target||!/^http:\/\/127\.0\.0\.1:4173\//.test(target.url))throw new Error('Refusing a non-project tab');
const source=JSON.parse(await readFile('models/design-data.json','utf8')),app=await readFile('studio.js','utf8'),revision=app.match(/ASSET_REVISION = '([^']+)'/)[1],prefix='v'+revision.replaceAll('.','');
const renderNames=['overall','living','dining','master','bedroom-b','study','kitchen','master-bath','guest-bath','balcony','bay-master','bay-tea','bay-living','entry-storage','sideboard'];
const hashes=requireImages?Object.fromEntries(await Promise.all(renderNames.map(async name=>{const file=`assets/blender-renders/${name}.jpg`;return[file,createHash('sha256').update(await readFile(file)).digest('hex')]}))):{};
const expectedParts=source.storageFitouts.flatMap(f=>f.parts.map(p=>({id:p.id,fitout:f.id,bbox:[p.x,p.y,p.w,p.d],z:p.zCm,h:p.hCm})));
const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true})});
let next=0;const pending=new Map(),exceptions=[],checks=[],screenshots=[];
ws.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.method==='Runtime.exceptionThrown')exceptions.push(message.params.exceptionDetails);if(pending.has(message.id)){const p=pending.get(message.id);pending.delete(message.id);clearTimeout(p.timer);message.error?p.reject(new Error(JSON.stringify(message.error))):p.resolve(message.result)}});
function call(method,params={}){return new Promise((resolve,reject)=>{const id=++next,timer=setTimeout(()=>{pending.delete(id);reject(new Error(method+' timed out'))},45000);pending.set(id,{resolve,reject,timer});ws.send(JSON.stringify({id,method,params}))})}
async function evaluate(expression){const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value}
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function check(name,pass,detail){checks.push({name,pass:!!pass,...(detail===undefined?{}:{detail})});console.log(`${pass?'PASS':'FAIL'} ${name}${!pass&&detail?' '+JSON.stringify(detail):''}`)}
async function waitFor(expression,timeout=45000){const until=Date.now()+timeout;while(Date.now()<until){if(await evaluate(expression))return true;await pause(300)}return false}
async function click(selector){await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);await pause(100)}
async function closeDialogs(){await evaluate(`document.querySelectorAll('dialog[open]').forEach(d=>d.close())`)}
async function layout(selector){return evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)}),r=e.getBoundingClientRect();return{left:r.left,right:r.right,top:r.top,bottom:r.bottom,overflow:e.scrollWidth>e.clientWidth+2,inside:r.left>=0&&r.right<=innerWidth+1&&r.top>=0&&r.bottom<=innerHeight+1}})()`)}
async function shot(name){const r=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false}),out=path.resolve(`tmp/${prefix}-${name}.png`);await writeFile(out,Buffer.from(r.data,'base64'));screenshots.push(out)}
async function validateSVG(text,label){
  const actual=await evaluate(`(()=>{const d=new DOMParser().parseFromString(${JSON.stringify(text)},'image/svg+xml');return{parts:[...d.querySelectorAll('[data-storage-part-id]')].map(p=>({id:p.getAttribute('data-storage-part-id'),fitout:p.getAttribute('data-storage-id'),bbox:['x','y','width','height'].map(k=>+p.getAttribute(k)),z:+p.getAttribute('data-z-cm'),h:+p.getAttribute('data-h-cm')})),bayParts:d.querySelectorAll('[data-fitout-id]').length,bays:d.querySelectorAll('[data-bay-window]').length,northDoor:d.querySelector('[data-opening-id="door_bath_1"]')?.getAttribute('y1')}})()`);
  check(`${label}: all ten source part boxes and heights`,actual.parts.length===expectedParts.length&&expectedParts.every(p=>actual.parts.some(a=>JSON.stringify(a)===JSON.stringify(p))),actual.parts);
  check(`${label}: bay and bath geometry retained`,actual.bays===3&&actual.bayParts===source.bayFitouts.flatMap(f=>f.parts).length&&actual.northDoor==='328',actual);
}
await mkdir('tmp',{recursive:true});
try{
  await call('Runtime.enable');await call('Page.enable');await call('Performance.enable');await call('Network.enable');await call('Network.setCacheDisabled',{cacheDisabled:true});
  for(const mode of ['desktop','mobile']){
    await closeDialogs();await call('Emulation.setDeviceMetricsOverride',{width:mode==='mobile'?390:1440,height:mode==='mobile'?844:1000,deviceScaleFactor:1,mobile:mode==='mobile'});
    await evaluate(`history.replaceState(null,'',location.pathname+'?v=${revision}')`);await call('Page.reload',{ignoreCache:true});
    const ready=await waitFor(`document.querySelector('#model-loading')?.hidden===true&&document.querySelectorAll('[data-storage-card]').length===2`);
    check(`${mode}: 3D model loaded`,ready&&await evaluate(`document.querySelector('#model-fallback').hidden`));
    check(`${mode}: document has no horizontal overflow`,await evaluate(`document.documentElement.scrollWidth<=innerWidth+2`));
    check(`${mode}: storage entry visible`,(await layout('#view-storage-fitout')).inside,await layout('#view-storage-fitout'));
    if(requireImages){const actual=await evaluate(`(async()=>Object.fromEntries(await Promise.all(${JSON.stringify(Object.keys(hashes))}.map(async path=>{const u=new URL(path,document.baseURI);u.searchParams.set('v',${JSON.stringify(revision)});const r=await fetch(u,{cache:'no-store'});return[path,r.ok?[...new Uint8Array(await crypto.subtle.digest('SHA-256',await r.arrayBuffer()))].map(n=>n.toString(16).padStart(2,'0')).join(''):'HTTP '+r.status]}))))()`);for(const [file,hash]of Object.entries(hashes))check(`${mode}: browser/disk SHA ${file}`,actual[file]===hash,{expected:hash,actual:actual[file]})}
    await pause(900);await shot(`${mode}-storage-model`);
    const before=Object.fromEntries((await call('Performance.getMetrics')).metrics.map(m=>[m.name,m.value]));await pause(1300);const after=Object.fromEntries((await call('Performance.getMetrics')).metrics.map(m=>[m.name,m.value]));check(`${mode}: idle layout stable`,after.LayoutCount-before.LayoutCount<=1,{layouts:after.LayoutCount-before.LayoutCount});
    await click('[data-view="plan"]');await validateSVG(await evaluate(`document.querySelector('#floor-plan svg').outerHTML`),`${mode} live SVG`);await shot(`${mode}-storage-plan`);
    const exported=await evaluate(`(async()=>{const original={create:URL.createObjectURL,open:window.open,click:HTMLAnchorElement.prototype.click};let blob,opened=0,downloaded=0;try{URL.createObjectURL=b=>{blob=b;return 'blob:qa-no-navigation'};window.open=()=>{opened++;return{}};HTMLAnchorElement.prototype.click=function(){downloaded++};document.querySelector('#open-plan').click();const openText=await blob.text();document.querySelector('#download-plan').click();return{openText,downloadText:await blob.text(),opened,downloaded,view:document.querySelector('#workspace').dataset.view}}finally{URL.createObjectURL=original.create;window.open=original.open;HTMLAnchorElement.prototype.click=original.click}})()`);
    check(`${mode}: plan open/export preserves state`,exported.openText===exported.downloadText&&exported.opened===1&&exported.downloaded===1&&exported.view==='plan');await validateSVG(exported.openText,`${mode} exported SVG`);
    await click('[data-view="model"]');await click('#view-storage-fitout');check(`${mode}: storage dialog fits viewport`,(await layout('#storage-dialog')).inside&&!(await layout('#storage-dialog')).overflow,await layout('#storage-dialog'));
    if(requireImages)check(`${mode}: visible storage images ready`,await waitFor(`[...document.querySelectorAll('#storage-fitout-cards img')].filter(i=>{const r=i.getBoundingClientRect();return r.bottom>0&&r.top<innerHeight}).every(i=>i.complete&&i.naturalWidth>0&&!i.parentElement.disabled)`,15000));
    await shot(`${mode}-storage-overview`);
    for(const fitout of source.storageFitouts){
      const selector=`[data-storage-card="${fitout.id}"]`;
      await evaluate(`(()=>{const c=document.querySelector(${JSON.stringify(selector)});c.querySelector('details').open=true;c.scrollIntoView({block:'start'})})()`);await pause(200);
      check(`${mode}: ${fitout.id} card no overflow`,!(await layout(selector)).overflow);
      check(`${mode}: ${fitout.id} close reachable`,(await layout('#storage-dialog>.dialog-close')).inside);
      check(`${mode}: ${fitout.id} source copy complete`,await evaluate(`(()=>{const t=document.querySelector(${JSON.stringify(selector)}).textContent;return ${JSON.stringify([fitout.summary,...fitout.dimensions,...fitout.conditions])}.every(s=>t.includes(s))})()`));
      const refs=await evaluate(`[...document.querySelectorAll(${JSON.stringify(selector+' a[href]')})].map(a=>({href:a.href,target:a.target,rel:a.rel}))`),expectedRefs=fitout.references.map(id=>source.designReferences.find(r=>r.id===id));check(`${mode}: ${fitout.id} original reference links safe/exact`,refs.length===expectedRefs.length&&expectedRefs.every(r=>refs.some(a=>a.href===r.url&&a.target==='_blank'&&a.rel.includes('noopener')&&a.rel.includes('noreferrer'))),refs);
      const elevation=await evaluate(`[...document.querySelectorAll(${JSON.stringify(selector+' [data-elevation-part-id]')})].map(e=>({id:e.getAttribute('data-elevation-part-id'),sourceY:+e.getAttribute('data-source-y'),z:+e.getAttribute('data-source-z-cm'),w:+e.getAttribute('width'),h:+e.getAttribute('height'),depth:+e.getAttribute('data-depth-cm')}))`);check(`${mode}: ${fitout.id} elevation uses actual part lengths/heights`,elevation.length===fitout.parts.length&&fitout.parts.every(p=>elevation.some(e=>e.id===p.id&&e.sourceY===p.y&&e.z===p.zCm&&e.w===p.d&&e.h===p.hCm&&e.depth===p.w)),elevation);
      if(requireImages){const loaded=await waitFor(`(()=>{const i=document.querySelector(${JSON.stringify(selector+' img')});return i.complete&&i.naturalWidth>0&&!i.parentElement.disabled})()`,15000);check(`${mode}: ${fitout.id} image loaded`,loaded);if(loaded){await click(`[data-storage-render="${fitout.id}"]`);await waitFor(`document.querySelector('#large-render').complete&&document.querySelector('#large-render').naturalWidth>0`,10000);await evaluate(`document.querySelector('#large-render').decode().catch(()=>{})`);check(`${mode}: ${fitout.id} image modal fits`,await evaluate(`document.querySelector('#image-dialog').open&&document.querySelector('#storage-dialog').open`)&&(await layout('#image-dialog>.dialog-close')).inside);await shot(`${mode}-${fitout.id}-image`);await click('#image-dialog>.dialog-close');check(`${mode}: image close returns to storage`,await evaluate(`document.querySelector('#storage-dialog').open&&!document.querySelector('#image-dialog').open`))}}
      await evaluate(`document.querySelector(${JSON.stringify(selector+' .storage-elevation')}).scrollIntoView({block:'center'})`);await pause(100);await shot(`${mode}-${fitout.id}-elevation`);
      await evaluate(`document.querySelector(${JSON.stringify(selector+' details')}).scrollIntoView({block:'start'})`);await pause(100);await shot(`${mode}-${fitout.id}-conditions`);
      await click(`[data-storage-room="${fitout.id}"]`);check(`${mode}: ${fitout.id} returns to dining`,await evaluate(`!document.querySelector('#storage-dialog').open&&location.hash==='#dining'&&document.querySelector('#workspace').dataset.view==='model'`));
      check(`${mode}: dining card source dimensions`,await evaluate(`(()=>{const t=document.querySelector('#card-description').textContent;return t.includes('1750')&&t.includes('400')&&t.includes('2500')&&t.includes('800')&&t.includes('450')&&t.includes('1400')&&t.includes('850')&&t.includes('280')&&t.includes('非现场实测')})()`));
      await evaluate(`document.querySelector('#view-storage-fitout').scrollIntoView({block:'nearest'})`);check(`${mode}: dining storage action reachable`,(await layout('#view-storage-fitout')).inside);await click('#view-storage-fitout');
    }
    await evaluate(`document.querySelector('#storage-dialog').scrollTop=document.querySelector('#storage-dialog').scrollHeight`);await pause(100);check(`${mode}: storage footer close reachable`,(await layout('#storage-dialog>.dialog-close')).inside);check(`${mode}: storage conditions note complete`,await evaluate(`(()=>{const t=document.querySelector('#storage-assumptions').textContent;return ${JSON.stringify(source.storageDesign.assumptions)}.every(s=>t.includes(s))})()`));await shot(`${mode}-storage-notes`);await closeDialogs();
    await click('#open-project');await click('#project-storage-link');check(`${mode}: design notes link reaches storage`,await evaluate(`document.querySelector('#storage-dialog').open&&!document.querySelector('#project-dialog').open`));await closeDialogs();
    await click('#open-project');await click('#project-bay-link');check(`${mode}: existing three bay cards retained`,await evaluate(`document.querySelector('#bay-dialog').open&&document.querySelectorAll('[data-fitout-card]').length===3`));await closeDialogs();
  }
  check('no uncaught browser exceptions',exceptions.length===0,exceptions);
}catch(error){checks.push({name:'runner completed',pass:false,detail:error.stack});console.error(error.stack)}
finally{await closeDialogs().catch(()=>{});await call('Emulation.clearDeviceMetricsOverride').catch(()=>{});await call('Network.setCacheDisabled',{cacheDisabled:false}).catch(()=>{});ws.close();const report={at:new Date().toISOString(),revision,port,tabId,requireImages,passed:checks.every(c=>c.pass),checks,exceptions,screenshots},out=path.resolve(`tmp/qa-storage-ui${requireImages?'-images':''}.json`);await writeFile(out,JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,checks:checks.length,failures:checks.filter(c=>!c.pass),report:out,screenshots},null,2));if(!report.passed)process.exitCode=1}
