// Offline regression for the actual SVG implementation. Run: node tools/test_plan_geometry.mjs
// No browser, generated files, dependencies, or duplicate floor-plan renderer.
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';

const root = new URL('../', import.meta.url);
const source = await readFile(new URL('studio.js', root), 'utf8');
const data = JSON.parse(await readFile(new URL('models/design-data.json', root), 'utf8'));
const start = source.indexOf('function planFurniture(');
const end = source.indexOf('\nfunction exportPlan(', start);
assert.ok(start >= 0 && end > start, 'Actual planFurniture / makePlan functions must be discoverable');
const helpers = ['areaOf', 'centroid', 'escapeHTML', 'storageRoleName'].map(name => {
  const line = source.split(/\r?\n/).find(line => new RegExp(`^const ${name}\\s*=`).test(line));
  assert.ok(line, `Actual ${name} helper must exist`);
  return line;
}).join('\n');
const host = { innerHTML: '' };
const context = vm.createContext({
  data,
  $: selector => { assert.equal(selector, '#floor-plan'); return host; },
  $$: () => [], // Only room event handlers; do not change generated geometry.
  roomDescription: id => ({ name: data.rooms.find(room => room.id === id)?.name || id }),
});
vm.runInContext(`${helpers}\n${source.slice(start, end)}\nmakePlan();`, context, { timeout: 1000 });
const svg = host.innerHTML;
assert.ok(svg.includes('data-sliding-door="door_kitchen"'),'Kitchen shows tracked slider, not one fixed glass pane');
assert.equal((svg.match(/data-sliding-panel=/g)||[]).length,3);
assert.ok(svg.includes('1700 三轨推拉'));
const tags = (html, marker) => [...html.matchAll(/<(?:rect|line|path|polygon|g)\b[^>]*>/g)].map(match => match[0]).filter(tag => tag.includes(marker));
const attribute = (tag, name) => tag.match(new RegExp(`(?:^|\\s)${name}="([^"]*)"`))?.[1];
const coordinates = (tag, names) => names.map(name => Number(attribute(tag, name)));
const one = (html, marker) => { const found = tags(html, marker); assert.equal(found.length, 1, marker); return found[0]; };

for (const expected of [
  { id: 'bed_a', direction: 'east', mattress: [467.5, 87, 200, 150], headX: 671.25 },
  { id: 'bed_b', direction: 'west', mattress: [27.5, 60, 200, 135], headX: 23.75 },
]) {
  const item = data.furniture.find(f => f.id === expected.id);
  assert.ok(item, expected.id);
  context.item = item;
  const rendered = vm.runInContext('planFurniture(item)', context);
  assert.equal(attribute(one(rendered, 'data-bed-direction'), 'data-bed-direction'), expected.direction);
  assert.deepEqual(coordinates(one(rendered, 'data-furniture-frame'), ['x','y','width','height']), [item.x,item.y,item.w,item.d]);
  assert.equal(attribute(one(rendered, 'data-furniture-frame'), 'transform'), undefined, 'Final bbox must not be rotated again');
  assert.deepEqual(coordinates(one(rendered, 'data-bed-mattress'), ['x','y','width','height']), expected.mattress);
  const head = one(rendered, 'data-bed-headboard');
  assert.deepEqual(coordinates(head, ['x1','x2','stroke-width']), [expected.headX,expected.headX,7.5]);
  assert.equal(tags(rendered, 'data-bed-pillow').length, 2);
  assert.ok(svg.includes(rendered), `${expected.id} generated by actual makePlan`);
}

for (const [id, points] of Object.entries({
  bath_1: '422,334 675,334 675,487 522,487 522,463 422,463',
  bath_2: '422,475 510,475 510,499 675,499 675,620 422,620',
})) {
  assert.equal(attribute(one(svg, `data-plan-room="${id}"`), 'points'), points, `${id} retains six-point stepped boundary`);
  assert.equal(data.rooms.find(r => r.id === id).points.map(p => p.join(',')).join(' '), points, `${id} matches shared source`);
}
assert.deepEqual(coordinates(one(svg, 'data-opening-id="door_bath_1"'), ['x1','y1','x2','y2']), [432,328,507,328], 'Main bath north door enters master');
assert.equal(tags(svg, 'data-bay-window').length, 3, 'Keep all three bay projections');
assert.equal(attribute(one(svg, 'data-vanity-id="vanity_main"'), 'data-vanity-face'), 'east');
assert.equal(attribute(one(svg, 'data-vanity-id="vanity_main"'), 'data-vanity-back'), 'west');
assert.equal(attribute(one(svg, 'data-vanity-id="vanity_guest"'), 'data-vanity-back'), 'north');
assert.equal(tags(svg, 'data-plan-room=').length, data.rooms.filter(r => r.id !== 'dining').length);
const fitoutParts = data.bayFitouts.flatMap(fitout => fitout.parts.map(part => ({fitout,part})));
assert.equal(fitoutParts.length,13,'Three bay functions retain thirteen explicit 3D component envelopes');
assert.equal(tags(svg,'data-part-id=').length,fitoutParts.length,'Each actual part has exactly one source rectangle');
for(const {fitout,part} of fitoutParts){
  const rect=one(svg,`data-part-id="${part.id}"`);
  assert.equal(attribute(rect,'data-fitout-id'),fitout.id);
  assert.equal(attribute(rect,'data-fitout-role'),part.role);
  assert.deepEqual(coordinates(rect,['x','y','width','height','data-z-cm','data-h-cm']),[part.x,part.y,part.w,part.d,part.zCm,part.hCm],`${part.id} exact cm footprint and height from shared data`);
  assert.equal(attribute(rect,'transform'),undefined,`${part.id} must not rotate its final world bbox twice`);
  context.fitout=fitout;context.part=part;
  const actual=vm.runInContext('planFitoutPart(fitout,part)',context);
  assert.ok(svg.includes(actual),`${part.id} rendered by actual makePlan`);
  if(part.role==='chair'){
    const lines=tags(actual,'<line');
    assert.equal(lines.length,1,`${part.id} one actual backrest line`);
    const expected=part.face==='east'?[part.x+3,part.y+5,part.x+3,part.y+part.d-5]:[part.x+part.w-3,part.y+5,part.x+part.w-3,part.y+part.d-5];
    assert.deepEqual(coordinates(lines[0],['x1','y1','x2','y2']),expected,`${part.id} back is opposite east/west seating face`);
  }
  if(['desk_support','desk_accessories','ledge_objects'].includes(part.role)){
    assert.equal(attribute(rect,'fill'),'none',`${part.id} empty aggregate envelope is not drawn as solid storage`);
    assert.equal(attribute(rect,'stroke'),'none');
  }
}
const teaWindow=data.windows.find(w=>w.id==='window_b');
assert.deepEqual([teaWindow.sillCm,teaWindow.heightCm,teaWindow.baselineSillCm,teaWindow.baselineHeightCm],[43,187,90,140],'Low tea ledge remains a conditional scenario with original 90 cm baseline');
assert.ok(teaWindow.designScenario);
assert.equal(data.bayDesign.measured,false);
assert.ok(svg.includes('条件设计，非施工图'),'Actual SVG exports conditional-design limitations');
const masterParts=data.bayFitouts.find(f=>f.roomId==='room_a').parts;
assert.deepEqual(masterParts.map(p=>p.id).sort(),['a_accessories','a_chair','a_desktop','a_support'],'No detached master desk or duplicate rear ledge');
assert.equal(masterParts.filter(p=>p.role==='desktop').length,1);
assert.equal(masterParts.filter(p=>p.role==='chair').length,1);
const masterTop=one(svg,'data-part-id="a_desktop"');
assert.deepEqual(coordinates(masterTop,['x','y','width','height','data-z-cm','data-h-cm']),[432,-53,146,130,90.1,3],'One actual SVG top connects bay to 65 cm interior overhang without lowering the solid sill');
for(const removed of ['次卧书桌','次卧书椅']){
  assert.ok(!data.furniture.some(f=>f.name===removed),`${removed} removed from shared source`);
  assert.ok(!svg.includes(removed),`${removed} removed from actual generated SVG`);
}
assert.ok(!svg.includes('data-part-id="a_ledge"')&&!svg.includes('data-part-id="a_ledge_objects"'));
const storageParts=data.storageFitouts.flatMap(fitout=>fitout.parts.map(part=>({fitout,part})));
assert.equal(storageParts.length,24,'V3.1.1 has four east-entry parts and twenty L-shaped dining parts');
assert.equal(data.furniture.filter(f=>f.storageFitoutId).length,4,'Source footprint wrappers are entry, long arm, return, and blind corner');
assert.ok(!data.furniture.some(f=>f.id==='entry_bench'),'Old fixed entry bench removed');
const entrySource=data.storageFitouts.find(f=>f.type==='entry');
assert.ok(entrySource.parts.every(p=>p.face==='west'&&p.segmentId==='east-entry'),'Right-hand east shoe cabinet must face the west passage, not copied from a mirrored photo');
for(const [id,bbox]of Object.entries({e_shoe_lower:[495,1320,34,65],e_shoe_upper:[501,1320,28,65],d4_base:[212.5,1220,40,129],d4_upper:[212.5,1220,28,141],d_return_base:[252.5,1349,122.5,40],d_return_upper:[240.5,1361,134.5,28],d_corner_base:[212.5,1349,40,40],d_corner_upper:[212.5,1361,28,28]})){
  const part=storageParts.find(item=>item.part.id===id)?.part;assert.ok(part,id);assert.deepEqual([part.x,part.y,part.w,part.d],bbox,`${id} V3.1.1 directional source anchor; upper and lower envelopes are not forcibly aligned`);
}
assert.equal(tags(svg,'data-storage-part-id=').length,storageParts.length,'Exactly one source rectangle per physical storage part in actual floor plan');
for(const {fitout,part} of storageParts){
  const rect=one(svg,`data-storage-part-id="${part.id}"`);
  assert.equal(attribute(rect,'data-storage-id'),fitout.id);
  assert.equal(attribute(rect,'data-storage-role'),part.role);
  assert.equal(attribute(rect,'data-storage-face'),part.face||fitout.face||'east');
  assert.equal(attribute(rect,'data-storage-segment'),part.segmentId||part.source?.segmentId||part.wallSide||part.face||fitout.face||'east');
  assert.deepEqual(coordinates(rect,['x','y','width','height','data-z-cm','data-h-cm']),[part.x,part.y,part.w,part.d,part.zCm,part.hCm],`${part.id} source centimetres and height preserved`);
  assert.equal(attribute(rect,'transform'),undefined,'World plan box must not rotate its 40 cm depth and along-wall length twice');
  context.fitout=fitout;context.part=part;
  assert.ok(svg.includes(vm.runInContext('planStoragePart(fitout,part)',context)),`${part.id} from actual renderer`);
  if(part.role.includes('niche')||part.role.includes('accessories'))assert.equal(attribute(rect,'fill'),'none',`${part.id} does not falsely fill an open niche in plan`);
  const fronts=tags(svg,`data-storage-front-for="${part.id}"`);
  if(part.role.includes('blind')){assert.equal(fronts.length,0,`${part.id} blind zone is not a usable front cabinet`);assert.equal(tags(svg,`data-storage-blind-for="${part.id}"`).length,1)}
  else if(!part.role.includes('niche')&&!part.role.includes('accessories')&&(part.doorStyle||part.doorPanels)){
    assert.equal(fronts.length,1);const {x,y,w,d}=part;
    const expected=part.face==='west'?[x+2,y+3,x+2,y+d-3]:part.face==='north'?[x+3,y+2,x+w-3,y+2]:part.face==='south'?[x+3,y+d-2,x+w-3,y+d-2]:[x+w-2,y+3,x+w-2,y+d-3];
    assert.deepEqual(coordinates(fronts[0],['x1','y1','x2','y2']),expected,`${part.id} front edge follows source facing, never a mirrored east default`);
  }
}
for(const wrapper of data.furniture.filter(f=>f.storageFitoutId)){
  context.item=wrapper;
  assert.ok(!svg.includes(vm.runInContext('planFurniture(item)',context)),`${wrapper.id} does not add a duplicate solid wrapper behind parts`);
}
for(const [name,bbox] of Object.entries({'四人餐桌':[330,1110,120,70],'餐椅北1':[338,1052.5,44,45],'餐椅北2':[398,1052.5,44,45],'餐椅南1':[338,1192.5,44,45],'餐椅南2':[398,1192.5,44,45]})){
  const item=data.furniture.find(f=>f.name===name);assert.deepEqual([item.x,item.y,item.w,item.d],bbox,`${name} group move`);
  context.item=item;assert.ok(svg.includes(vm.runInContext('planFurniture(item)',context)),`${name} actual drawing shares exact group coordinates`);
}
const elevationStart=source.indexOf('function storageElevation('),elevationEnd=source.indexOf('\nfunction showStorageFitouts(',elevationStart);
assert.ok(elevationStart>=0&&elevationEnd>elevationStart);
vm.runInContext(source.slice(elevationStart,elevationEnd),context);
for(const fitout of data.storageFitouts){
  context.fitout=fitout;const elevation=vm.runInContext('storageElevation(fitout)',context);
  const segmentFor=p=>p.segmentId||p.source?.segmentId||p.wallSide||p.face||fitout.face||'east';
  const groupKeys=new Set(fitout.parts.map(p=>`${segmentFor(p)}|${p.face||fitout.face||'east'}`));
  assert.equal((elevation.match(/<figure\b/g)||[]).length,groupKeys.size,'Distinct segments/facings are not overlaid as a fictitious single east elevation');
  for(const part of fitout.parts){
    const face=part.face||fitout.face||'east',same=fitout.parts.filter(p=>segmentFor(p)===segmentFor(part)&&(p.face||fitout.face||'east')===face),axis=['north','south'].includes(face)?'x':'y',length=axis==='x'?'w':'d',depth=axis==='x'?'d':'w';
    const min=Math.min(...same.map(p=>p[axis])),max=Math.max(...same.map(p=>p[axis]+p[length])),top=Math.max(...same.map(p=>p.zCm+p.hCm));
    const rect=one(elevation,`data-elevation-part-id="${part.id}"`);
    assert.equal(attribute(rect,'data-elevation-face'),face);assert.equal(attribute(rect,'data-elevation-segment'),segmentFor(part));
    assert.deepEqual(coordinates(rect,['x','y','width','height','data-source-x','data-source-y','data-source-z-cm','data-depth-cm']),[['east','north'].includes(face)?max-part[axis]-part[length]:part[axis]-min,top-part.zCm-part.hCm,part[length],part.hCm,part.x,part.y,part.zCm,part[depth]],`${part.id} actual ${face} elevation has true segment length/height, not plan depth`);
    if(part.role.includes('niche')){
      assert.equal(attribute(rect,'stroke'),'none',`${part.id} semantic bbox cannot imply fictitious end panels`);
      const [x,y,w,h]=coordinates(rect,['x','y','width','height']);
      const expected={top:[x,y,x+w,y],bottom:[x,y+h,x+w,y+h]};
      if(part.role==='sideboard_corner_niche')expected['west-back']=[x+w,y,x+w,y+h];
      else{if(!part.omitStartPanel)expected.start=[x+w,y,x+w,y+h];if(!part.omitEndPanel)expected.end=[x,y,x,y+h]}
      const edges=tags(elevation,`data-elevation-niche-edge-for="${part.id}"`);
      assert.equal(edges.length,Object.keys(expected).length,`${part.id} only retained end panels are outlined`);
      for(const [name,coords]of Object.entries(expected))assert.deepEqual(coordinates(one(elevation,`data-elevation-niche-edge-for="${part.id}" data-niche-edge="${name}"`),['x1','y1','x2','y2']),coords,`${part.id} ${name} follows the complete module rotation`);
    }
    if(part.role==='sideboard_base')assert.equal(tags(elevation,`data-elevation-drawer-for="${part.id}"`).length,part.drawerPanels??part.drawerCount??2,`${part.id} drawer quantity follows source; zero means full-height closed fronts`);
  }
}
// Direction fixtures exercise the actual renderer independently of which source faces currently exist.
context.fitout={title:'Direction regression',segments:[{id:'left',title:'左段'}],parts:[{id:'west-a',role:'shoe_lower',segmentId:'left',face:'west',x:495,y:1320,w:34,d:25,zCm:0,hCm:100},{id:'west-b',role:'shoe_lower',segmentId:'left',face:'west',x:495,y:1345,w:34,d:40,zCm:0,hCm:100},{id:'north-a',role:'sideboard_base',segmentId:'return',face:'north',x:252.5,y:1349,w:62.5,d:40,zCm:0,hCm:85},{id:'north-b',role:'sideboard_blind_base',segmentId:'return',face:'north',x:315,y:1349,w:60,d:40,zCm:0,hCm:85}]};
const directions=vm.runInContext('storageElevation(fitout)',context);
for(const [id,expected]of Object.entries({'west-a':[0,0,25,100],'west-b':[25,0,40,100],'north-a':[60,0,62.5,85],'north-b':[0,0,60,85]}))assert.deepEqual(coordinates(one(directions,`data-elevation-part-id="${id}"`),['x','y','width','height']),expected,`${id} screen direction regression`);
assert.ok(directions.includes('左北右南')&&directions.includes('左东右西'));
assert.equal(tags(directions,'data-elevation-blind-area').length,1);
// A canonical start/end is not simply global min/max after a 180 degree turn.
// Frontally, start remains screen-right and end screen-left for all four faces.
for(const face of ['east','west','north','south']){
  const vertical=['east','west'].includes(face),part={id:`niche-${face}`,role:'sideboard_niche',face,x:100,y:200,w:vertical?40:80,d:vertical?80:40,zCm:85,hCm:65,omitStartPanel:true};
  context.fitout={title:'Rotated niche regression',parts:[part]};
  let actual=vm.runInContext('storageElevation(fitout)',context);
  assert.equal(tags(actual,'data-niche-edge="start"').length,0,`${face}: omitted canonical start cannot reappear on either side`);
  assert.deepEqual(coordinates(one(actual,'data-niche-edge="end"'),['x1','y1','x2','y2']),[0,0,0,65],`${face}: retained canonical end is the left front edge`);
  part.omitStartPanel=false;part.omitEndPanel=true;
  actual=vm.runInContext('storageElevation(fitout)',context);
  assert.equal(tags(actual,'data-niche-edge="end"').length,0,`${face}: omitted canonical end cannot reappear`);
  assert.deepEqual(coordinates(one(actual,'data-niche-edge="start"'),['x1','y1','x2','y2']),[80,0,80,65],`${face}: retained canonical start is the right front edge`);
}
console.log(`PASS: actual SVG; beds/baths/bays preserved, ${data.bayFitouts.flatMap(f=>f.parts).length} bay parts, ${storageParts.length} exact storage boxes/fronts without duplicate wrappers, and correctly directed segmented elevations.`);
