// Offline regression for the actual SVG implementation. Run: node tools/test_plan_geometry.mjs
// No browser, generated files, dependencies, or duplicate floor-plan renderer.
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';

const root = new URL('../', import.meta.url);
const source = await readFile(new URL('studio.js', root), 'utf8');
const data = JSON.parse(await readFile(new URL('models/design-data.json', root), 'utf8'));
const start = source.indexOf('function planFurniture(');
const end = source.indexOf('\nfunction exportPlan(', start);
assert.ok(start >= 0 && end > start, 'Actual planFurniture / makePlan functions must be discoverable');
const helpers = ['areaOf', 'centroid', 'escapeHTML'].map(name => {
  const line = source.split(/\r?\n/).find(line => line.startsWith(`const ${name} = `));
  assert.ok(line, `Actual ${name} helper must exist`);
  return line;
}).join('\n');
const host = { innerHTML: '' };
const context = vm.createContext({
  data,
  $: selector => { assert.equal(selector, '#floor-plan'); return host; },
  $$: () => [], // Only room event handlers; do not change generated geometry.
  roomDescription: id => ({ name: data.rooms.find(room => room.id === id)?.name || id }),
});
vm.runInContext(`${helpers}\n${source.slice(start, end)}\nmakePlan();`, context, { timeout: 1000 });
const svg = host.innerHTML;
const tags = (html, marker) => [...html.matchAll(/<(?:rect|line|polygon|g)\b[^>]*>/g)].map(match => match[0]).filter(tag => tag.includes(marker));
const attribute = (tag, name) => tag.match(new RegExp(`(?:^|\\s)${name}="([^"]*)"`))?.[1];
const coordinates = (tag, names) => names.map(name => Number(attribute(tag, name)));
const one = (html, marker) => { const found = tags(html, marker); assert.equal(found.length, 1, marker); return found[0]; };

for (const expected of [
  { id: 'bed_a', direction: 'east', mattress: [467.5, 65, 200, 150], headX: 671.25 },
  { id: 'bed_b', direction: 'west', mattress: [27.5, 60, 200, 135], headX: 23.75 },
]) {
  const item = data.furniture.find(f => f.id === expected.id);
  assert.ok(item, expected.id);
  context.item = item;
  const rendered = vm.runInContext('planFurniture(item)', context);
  assert.equal(attribute(one(rendered, 'data-bed-direction'), 'data-bed-direction'), expected.direction);
  assert.deepEqual(coordinates(one(rendered, 'data-furniture-frame'), ['x','y','width','height']), [item.x,item.y,item.w,item.d]);
  assert.equal(attribute(one(rendered, 'data-furniture-frame'), 'transform'), undefined, 'Final bbox must not be rotated again');
  assert.deepEqual(coordinates(one(rendered, 'data-bed-mattress'), ['x','y','width','height']), expected.mattress);
  const head = one(rendered, 'data-bed-headboard');
  assert.deepEqual(coordinates(head, ['x1','x2','stroke-width']), [expected.headX,expected.headX,7.5]);
  assert.equal(tags(rendered, 'data-bed-pillow').length, 2);
  assert.ok(svg.includes(rendered), `${expected.id} generated by actual makePlan`);
}

for (const [id, points] of Object.entries({
  bath_1: '422,334 675,334 675,487 522,487 522,463 422,463',
  bath_2: '422,475 510,475 510,499 675,499 675,620 422,620',
})) {
  assert.equal(attribute(one(svg, `data-plan-room="${id}"`), 'points'), points, `${id} retains six-point stepped boundary`);
  assert.equal(data.rooms.find(r => r.id === id).points.map(p => p.join(',')).join(' '), points, `${id} matches shared source`);
}
assert.deepEqual(coordinates(one(svg, 'data-opening-id="door_bath_1"'), ['x1','y1','x2','y2']), [432,328,507,328], 'Main bath north door enters master');
assert.equal(tags(svg, 'data-bay-window').length, 3, 'Keep all three bay projections');
assert.equal(attribute(one(svg, 'data-vanity-id="vanity_main"'), 'data-vanity-face'), 'east');
assert.equal(attribute(one(svg, 'data-vanity-id="vanity_main"'), 'data-vanity-back'), 'west');
assert.equal(attribute(one(svg, 'data-vanity-id="vanity_guest"'), 'data-vanity-back'), 'north');
assert.equal(tags(svg, 'data-plan-room=').length, data.rooms.filter(r => r.id !== 'dining').length);
const fitoutParts = data.bayFitouts.flatMap(fitout => fitout.parts.map(part => ({fitout,part})));
assert.equal(fitoutParts.length,15,'Three bay functions retain fifteen explicit 3D component envelopes');
assert.equal(tags(svg,'data-part-id=').length,fitoutParts.length,'Each actual part has exactly one source rectangle');
for(const {fitout,part} of fitoutParts){
  const rect=one(svg,`data-part-id="${part.id}"`);
  assert.equal(attribute(rect,'data-fitout-id'),fitout.id);
  assert.equal(attribute(rect,'data-fitout-role'),part.role);
  assert.deepEqual(coordinates(rect,['x','y','width','height','data-z-cm','data-h-cm']),[part.x,part.y,part.w,part.d,part.zCm,part.hCm],`${part.id} exact cm footprint and height from shared data`);
  assert.equal(attribute(rect,'transform'),undefined,`${part.id} must not rotate its final world bbox twice`);
  context.fitout=fitout;context.part=part;
  const actual=vm.runInContext('planFitoutPart(fitout,part)',context);
  assert.ok(svg.includes(actual),`${part.id} rendered by actual makePlan`);
  if(part.role==='chair'){
    const lines=tags(actual,'<line');
    assert.equal(lines.length,1,`${part.id} one actual backrest line`);
    const expected=part.face==='north'?[part.x+5,part.y+part.d-3,part.x+part.w-5,part.y+part.d-3]:[part.x+part.w-3,part.y+5,part.x+part.w-3,part.y+part.d-5];
    assert.deepEqual(coordinates(lines[0],['x1','y1','x2','y2']),expected,`${part.id} back is opposite north/west seating face`);
  }
  if(['desk_support','desk_accessories','ledge_objects'].includes(part.role)){
    assert.equal(attribute(rect,'fill'),'none',`${part.id} empty aggregate envelope is not drawn as solid storage`);
    assert.equal(attribute(rect,'stroke'),'none');
  }
}
const teaWindow=data.windows.find(w=>w.id==='window_b');
assert.deepEqual([teaWindow.sillCm,teaWindow.heightCm,teaWindow.baselineSillCm,teaWindow.baselineHeightCm],[43,187,90,140],'Low tea ledge remains a conditional scenario with original 90 cm baseline');
assert.ok(teaWindow.designScenario);
assert.equal(data.bayDesign.measured,false);
assert.ok(svg.includes('条件设计，非施工图'),'Actual SVG exports conditional-design limitations');
console.log('PASS: actual planFurniture + makePlan; exact beds, stepped baths, suite north door, 3 bays, vanity orientation, 15 bay part dimensions / heights and three true chair orientations.');
