import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import * as core from '../design-editor-core.js';
const root=path.resolve(import.meta.dirname,'..');
let checks=0;const check=(condition,message)=>{assert.ok(condition,message);checks++;};
const deepFreeze=value=>{if(value&&typeof value==='object'){Object.freeze(value);Object.values(value).forEach(deepFreeze);}return value;};
const clone=value=>JSON.parse(JSON.stringify(value));
class MemoryStorage{constructor(){this.values=new Map();}getItem(key){return this.values.get(key)??null;}setItem(key,value){this.values.set(key,value);}removeItem(key){this.values.delete(key);}}

assert.deepEqual(core.measurePoints([0,0],[30,40]),{distanceMm:500,horizontalMm:300,verticalMm:400});checks++;
assert.deepEqual(core.measurePoints({x:5,y:7},{x:-25,y:-33}),{distanceMm:500,horizontalMm:300,verticalMm:400});checks++;
assert.throws(()=>core.measurePoints([NaN,0],[1,1]));checks++;
const shape=[[0,0],[400,0],[400,200],[200,200],[200,400],[0,400]],area=core.polygonAreaM2(shape);
check(area===12,'L-room shoelace area, not 16m2 bounding area');
check(core.footprintInsideEnvelope({x:0,y:0,w:200,d:400},shape),'Boundary touching rectangle accepted');
check(!core.footprintInsideEnvelope({x:150,y:150,w:200,d:200},shape),'L-notch rejected');
const uShape=[[0,0],[400,0],[400,400],[300,400],[300,100],[100,100],[100,400],[0,400]];
check(!core.footprintInsideEnvelope({x:50,y:50,w:300,d:300},uShape),'All four corners inside cannot bridge exterior U-notch');
const lInfo=core.selectionInfo({rooms:[{id:'L',name:'凹形房',points:shape}]},{type:'room',key:'L'});
check(lInfo.areaM2===12&&lInfo.dimensionsMm.width===4000&&lInfo.edgeLengthsMm.length===6,'Room edge lengths and bounding dimensions');
check(/不是房间净宽/.test(lInfo.note),'Bounding width does not masquerade as measured clear width');
assert.equal(core.furnitureKey({id:'bed_a',name:'床'}),'bed_a');assert.equal(core.furnitureKey({name:'椅子'}),'name:椅子');checks+=2;
for(const f of [{name:'衣柜',x:1,y:1,w:30,d:60},{name:'沙发背后浅储物柜',x:1,y:1,w:200,d:25},{id:'study_full_desk',name:'书桌',x:1,y:1,w:200,d:60},{name:'沙发',x:1,y:1,w:200,d:80,storageFitoutId:'x'},{name:'椅子',x:1,y:1,w:40,d:40,a:90}])check(!core.isMovableFurniture(f),'Custom/fixed/unsupported-rotation fixtures locked');

const storage=new MemoryStorage(),reports=[];
for(const id of ['wood','family','laundry']){
  const baseline=JSON.parse(fs.readFileSync(path.join(root,`models/schemes/${id}/design-data.json`),'utf8'));
  const before=JSON.stringify(baseline),manifest=JSON.parse(fs.readFileSync(path.join(root,`models/schemes/${id}/scene-manifest.json`),'utf8'));
  const ctx={schemeId:id,sourceFingerprint:manifest.sourceSha256,data:baseline},draft=core.createDraft(id,manifest.sourceSha256);deepFreeze(baseline);
  const choices=core.listSelections(baseline),movable=baseline.furniture.filter(core.isMovableFurniture);
  const equipmentCount=baseline.kitchenFitout.appliances.length+baseline.laundry.machines.filter(item=>!baseline.furniture.some(f=>f.id===item.id)).length;
  check(choices.length===baseline.furniture.length+baseline.rooms.length+baseline.windows.length+baseline.doors.length+equipmentCount,id+' all source selections and readonly equipment visible');
  const dishwasher=choices.find(item=>item.key==='equipment:kitchen_dishwasher');
  check(dishwasher.locked&&!dishwasher.movable&&dishwasher.dimensionsMm.width===600&&dishwasher.dimensionsMm.depth===600&&dishwasher.dimensionsMm.height===805,id+' exact read-only dishwasher body dimensions');
  check(core.validateMove(baseline,draft,dishwasher.key,{dx:1,dy:0},ctx).ok===false,id+' equipment selection cannot become a movable source object');
  if(id==='wood'){const washer=choices.find(item=>item.key==='equipment:laundry_washer');check(washer.locked&&washer.dimensionsMm.width===600&&washer.dimensionsMm.depth===530&&washer.dimensionsMm.height===840,'Wood aggregate laundry exposes individual washing machine body');}
  check(movable.some(f=>f.id==='bed_a')&&movable.some(f=>f.name==='三人沙发')&&movable.some(f=>f.name==='四人餐桌'),id+' beds sofa table movable');
  check(movable.filter(f=>f.productKey==='chair').length===4,id+' four bought dining chairs movable');
  check(!movable.some(f=>f.id==='study_full_desk'||f.name.includes('衣柜')||f.kitchenFitoutId||f.laundryFitoutId),id+' fitted fixtures immutable');
  const sofa=baseline.furniture.find(f=>f.name==='三人沙发'),key=core.furnitureKey(sofa),table=choices.find(s=>s.type==='furniture'&&s.name==='四人餐桌'),bed=choices.find(s=>s.key==='bed_a');
  check(table.dimensionsMm.height===740&&table.dimensionsMm.width===baseline.furniture.find(f=>f.name==='四人餐桌').w*10,id+' exact known purchased table dimensions');
  check(!Object.hasOwn(bed.dimensionsMm,'height')&&bed.heightUnknown,id+' no invented bed height');
  const window=choices.find(s=>s.type==='window'&&s.key==='balcony_north_opening');check(window.dimensionsMm.length===1420&&window.dimensionsMm.sill===1100,id+' actual opening endpoints in millimetres');
  draft.colors={wall:'#AaBbCc',floor:'#eee9df'};
  const move=core.validateMove(baseline,draft,key,{dx:1,dy:1},ctx);check(move.ok,id+' safe footprint movement valid');
  check(move.draft.offsets[key].dx===1&&move.data.furniture.find(f=>f.name===sofa.name).x===sofa.x+1,id+' offsets relative to baseline');
  assert.deepEqual(move.data.furniture.find(f=>f.name===sofa.name).rugCm,sofa.rugCm);checks++;
  assert.deepEqual(move.data.modelAddons,baseline.modelAddons);checks++;
  const second=core.validateMove(baseline,move.draft,key,{dx:2,dy:2},ctx);check(second.data.furniture.find(f=>f.name===sofa.name).x===sofa.x+2,id+' offsets do not accumulate twice');
  check(JSON.stringify(baseline)===before,id+' deep-frozen baseline remains untouched');
  check(core.validateMove(baseline,draft,key,{dx:1000,dy:1000},ctx).errors.some(e=>e.code==='outside'),id+' outside footprint hard rejected');
  check(core.validateMove(baseline,draft,'study_full_desk',{dx:1,dy:0},ctx).errors.some(e=>e.code==='locked'),id+' fitted desk cannot move');
  check(core.validateMove(baseline,draft,key,{dx:NaN,dy:0},ctx).errors.some(e=>e.code==='offset'),id+' NaN blocked');
  check(core.validateMove(baseline,draft,key,{dx:Infinity,dy:0},ctx).errors.some(e=>e.code==='offset'),id+' Infinity blocked');
  check(core.validateMove(baseline,draft,key,{dx:1e20,dy:0},ctx).errors.some(e=>e.code==='offset-range'),id+' huge offsets blocked');
  check(core.validateMove(baseline,draft,key,{dx:'1',dy:0},ctx).errors.some(e=>e.code==='offset'),id+' numeric strings not coerced');
  check(core.saveDraft(storage,move.draft,ctx).ok,id+' explicit local save succeeds');
  const loaded=core.loadDraft(storage,ctx);check(loaded.status==='loaded'&&loaded.draft.colors.wall==='#aabbcc',id+' load exact scheme and canonical colours');
  check(core.loadDraft(storage,{...ctx,sourceFingerprint:'new-source'}).status==='fingerprint-mismatch',id+' new source does not restore old offsets');
  check(core.loadDraft(storage,{...ctx,sourceFingerprint:'new-source'}).draft===null,id+' stale draft never applied');
  check(core.loadDraft(storage,{...ctx,schemeId:id+'-another'}).status==='empty',id+' scheme storage isolated');
  check(core.validateDraft({...draft,schemeId:'another'},ctx).errors.some(e=>e.code==='scheme'),id+' cross-scheme pasted payload rejected');
  check(core.validateDraft({...draft,schema:2},ctx).errors.some(e=>e.code==='schema'),id+' incompatible schema rejected');
  check(!core.validateDraft({...draft,colors:{wall:'red'}},ctx).ok,id+' arbitrary CSS rejected');
  check(!core.validateDraft({...draft,colors:{ceiling:'#ffffff'}},ctx).ok,id+' unknown colour category rejected');
  check(!core.validateDraft({...draft,offsets:{unknown:{dx:0,dy:0}}},ctx).ok,id+' unknown object rejected');
  const poisoned=JSON.parse(JSON.stringify(draft));poisoned.offsets=JSON.parse('{"__proto__":{"dx":1,"dy":1},"constructor":{"dx":0,"dy":0}}');
  check(!core.validateDraft(poisoned,ctx).ok&&Object.prototype.dx===undefined,id+' malicious offset keys cannot pollute prototypes');
  check(!core.validateDraft(JSON.parse('{"schema":1,"__proto__":{"polluted":true}}'),ctx).ok&&!{}.polluted,id+' malformed root does not pollute prototype');
  const changed=core.deriveData(baseline,move.draft,ctx);changed.furniture[0].x=99999;check(baseline.furniture[0].x!==99999,id+' derived clone has no shared nested objects');
  assert.throws(()=>core.deriveData(baseline,move.draft,{...ctx,sourceFingerprint:'changed'}),/正式模型已更新/);checks++;
  const broken=new MemoryStorage(),storageKey=core.draftStorageKey(id);broken.setItem(storageKey,'{broken');check(core.loadDraft(broken,ctx).status==='invalid',id+' corrupt JSON explicit');
  broken.setItem(storageKey,'x'.repeat(core.MAX_DRAFT_BYTES+1));check(core.loadDraft(broken,ctx).status==='invalid',id+' oversized local value refused');
  const denied={getItem(){throw Error('denied');},setItem(){throw Error('quota');},removeItem(){throw Error('blocked');}};
  check(core.loadDraft(denied,ctx).status==='unavailable',id+' read failure explicit');check(core.saveDraft(denied,draft,ctx).status==='unavailable',id+' write/quota failure explicit');check(core.clearDraft(denied,id).status==='unavailable',id+' delete failure explicit');
  check(core.clearDraft(broken,id).status==='cleared'&&broken.getItem(storageKey)===null,id+' clear is explicit and scheme-scoped');
  check(core.sourceFingerprint(baseline)===core.sourceFingerprint(clone(baseline)),id+' stable fallback fingerprint');
  reports.push({id,selectable:choices.length,movable:movable.length,lockedFurniture:baseline.furniture.length-movable.length});
}
check(storage.values.size===3,'One saved key per scheme, no account/cloud storage');
const fixture={unit:'cm',envelope:[[0,0],[500,0],[500,500],[0,500]],rooms:[],windows:[],doors:[{id:'door',x1:220,y1:250,x2:280,y2:250}],walls:[[0,250,500,250]],wallSpecs:[{coords:[0,250,500,250],thicknessCm:12}],furniture:[{id:'chair',name:'椅子',x:50,y:50,w:40,d:40},{id:'fixed',name:'定制柜',x:200,y:50,w:100,d:100,tone:'cabinet'}]};
const fctx={schemeId:'test',sourceFingerprint:'manifest-hash',data:fixture},fd=core.createDraft('test','manifest-hash');
let moved=core.validateMove(fixture,fd,'chair',{dx:100,dy:180},fctx);check(moved.ok&&moved.warnings.some(w=>w.code==='wall-overlap'),'Internal wall collision warns without claiming implementation safety');
moved=core.validateMove(fixture,fd,'chair',{dx:160,dy:0},fctx);check(moved.ok&&moved.warnings.some(w=>w.code==='furniture-overlap'),'Furniture projection overlap warns');
moved=core.validateMove(fixture,fd,'chair',{dx:60,dy:0},fctx);check(moved.warnings.some(w=>w.code==='clearance'&&w.gapMm===500),'Narrow interval carries a precise schematic warning');
moved=core.validateMove(fixture,fd,'chair',{dx:180,dy:180},fctx);check(moved.warnings.some(w=>w.code==='door-zone')&&!moved.warnings.some(w=>w.code==='wall-overlap'),'Door is a real wall gap but still needs a clearance warning');
console.log(JSON.stringify({passed:true,checks,schemes:reports,storage:'browser-local-per-scheme',constructionValidation:false},null,2));
